package ccs.com.vhr.mapper;

import ccs.com.vhr.model.HrRole;

public interface HrRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int insert(HrRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int insertSelective(HrRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    HrRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int updateByPrimaryKeySelective(HrRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int updateByPrimaryKey(HrRole record);
}